### ISSUE TITLE
The Yelp dataset can not be downloaded now

### ISSUE THREAD

**Issue by wwwxmu** [timbmg/Structured-Self-Attentive-Sentence-Embedding#1]
The Yelp dataset can not be downloaded now, can you send me the yelp dataset? Thank you!
my Email:  weiwei121451070@gmail.com

**Comment by timbmg** [comment]
I think you can also get it here: [https://www.yelp.com/dataset/download](https://www.yelp.com/dataset/download)

**Comment by wwwxmu** [comment]
![image](https://user-images.githubusercontent.com/12303465/53957602-b5b47080-4119-11e9-8953-209a3e6060d3.png)
confirm, is this?

**Comment by timbmg** [comment]
yes that's it

**Comment by wwwxmu** [comment]
Thank you so much!
